### ISSUE TITLE
Add conditional function override

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#1402]
### Problem

When a user is importing a library (e.g. _greet_person_) that uses a foreign function (e.g. `wave_hand`), but the function:

- Is not supported by the proving backend used
- Does not have a fallback implementation in ACVM

The Noir program would not be compilable as expected.

If an alternative implementation of `wave_hand` written in Noir is available in another library (e.g. _noir_gestures_), however, the current best way for the user to make use of it would be to:

1. Fork _greet_person_
2. Change all `wave_hand` within to use _noir_gestures_'s implementation instead
3. Consume the edited forked version of _greet_person_

Which is burdensome to both execute and maintain down the road.

### Happy Case

The user should be able to override all instances of `wave_hand` with a simple config edit:

**_Nargo.toml_ before override:**

```toml
[package]
authors = [""]
compiler_version = "0.1"

[dependencies]
greet_person = { path = "./path/to/greet_person" }
```

**_Nargo.toml_ after override:**

```toml
[package]
authors = [""]
compiler_version = "0.1"

[dependencies]
greet_person = { path = "./path/to/greet_person" }

[override.wave_hand]
greet_person = { path = "./path/to/noir_gestures" }
```

The overriding function should have the same function signature as the original function.

This might also be useful if e.g. the original library uses a slow Noir implementation, where the user can override it with a fast blackbox implementation.

#### Conditional compilation

We can opt for some form of [conditional compilation](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition/conditional-compilation.html) instead of config changes, but I didn't manage to picture a decent approach.

#### Strictly require ACVM fallback

We can require a fallback implementation in ACVM must be added for each foreign function addition to the Noir _stdlib_.

This might be undesirable in terms of engineering efforts and speed on delivering foreign functions already usable with certain proving backends.

### Additional Context

The new `override` keyword was chosen instead of:
- `patch` as to reserve the keyword for matching behavior with [how it is used in Rust](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#overriding-dependencies) in case if we decide to add it in down the road
- `replace` as to avoid confusion with how [the same keyword was used in Rust](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-replace-section)

### Would you like to submit a PR for this Issue?

No
