### ISSUE TITLE
Consider passing through `TARGET_CC` & `TARGET_AR` in `Cross.toml` for rustls

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#2278]
According to the `ring` (dependency of `rustls`), the `TARGET_CC` and `TARGET_AR` env variables are required to cross-compile it.

Our cross-compilation seems fine, but we might want to provide these in the `Cross.toml` file. 🤷 

```toml
[target.x86_64-unknown-linux-gnu.env]
passthrough = [
    "TARGET_CC=x86_64-linux-gnu-gcc",
    "TARGET_AR=x86_64-linux-gnu-ar",
]

[target.x86_64-unknown-linux-musl.env]
passthrough = [
    "TARGET_CC=x86_64-linux-musl-gcc",
    "TARGET_AR=x86_64-linux-musl-ar",
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "TARGET_CC=aarch64-linux-gnu-gcc",
    "TARGET_AR=aarch64-linux-gnu-ar",
]

[target.aarch64-unknown-linux-musl.env]
passthrough = [
    "TARGET_CC=aarch64-linux-musl-gcc",
    "TARGET_AR=aarch64-linux-musl-ar",
]
```
