### ISSUE TITLE
Cyclic dependencies cause nargo to stack overflow

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#2295]
### Aim

Nargo panics with a stack overflow when given the following TOML:
```toml
[package]
name = "baz"
type = "bin"
authors = [""]
compiler_version = "0.9.0"

[dependencies]
foo_bar = { path = "./" }
```

### Expected Behavior

Dependency paths should be checked for cycles and a proper error should be given instead of panicing with a stack overflow

### Bug

Panic instead of a good error message.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

Maybe
