### ISSUE TITLE
Using the resulting slice from to_radix in signature verification fails the verification

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#2421]
### Aim

Tried to use the resulting bytes from a field decomposition as input to ECDSA & schnorr signature verification.

### Expected Behavior

The verification should pass the same as if the decomposition was done outside the circuit.

### Bug

Try executing this modified schnorr e2e test:
```rust
use dep::std;

// Note: If main has any unsized types, then the verifier will never be able
// to figure out the circuit instance
fn main(message: [u8; 10], message_field: Field, pub_key_x: Field, pub_key_y: Field, signature: [u8; 64]) {
    let message_field_bytes = message_field.to_be_bytes(10);
    for i in 0..10 {
        assert(message[i] == message_field_bytes[i]);
    }
    // Is there ever a situation where someone would want 
    // to ensure that a signature was invalid?
    let valid_signature = std::schnorr::verify_signature(pub_key_x,pub_key_y,signature, message_field_bytes);
    assert(valid_signature);
}
```
If you try to pass message_field_bytes it will fail, but if you pass message it will pass.
Prover.toml:
```toml
message = [0,1,2,3,4,5,6,7,8,9]
message_field = "0x010203040506070809"
pub_key_x = "0x17cbd3ed3151ccfd170efe1d54280a6a4822640bf5c369908ad74ea21518a9c5"
pub_key_y = "0x0e0456e3795c1a31f20035b741cd6158929eeccd320d299cfcac962865a6bc74"
signature = [
    5, 202, 31, 146, 81, 242, 246, 69, 43, 107, 249, 153, 198, 44, 14, 111, 191, 121, 137, 166, 
    160, 103, 18, 181, 243, 233, 226, 95, 67, 16, 37, 128, 85, 76, 19, 253, 30, 77, 192, 53, 138, 
    205, 69, 33, 236, 163, 83, 194, 84, 137, 184, 221, 176, 121, 179, 27, 63, 70, 54, 16, 176, 
    250, 39, 239,
]
```

This is a regression, since using the output of to_be_bytes as input to a signature verification was working previously in aztec account contracts. This started happening after the rework of slices https://github.com/noir-lang/noir/pull/2347 but looking at the PR content I don't understand why signature verifications would fail using the new slices :thinking: 

### To Reproduce

1.
2.
3.
4.

### Installation Method

Compiled from source

### Would you like to submit a PR for this Issue?

No
