### ISSUE TITLE
Incompatible compiler version in package noir_aztec.

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#3396]
### Aim

I want to run `nargo fmt` on my aztec contract.

### Expected Behavior

I should be able to run `nargo fmt` in my Aztec contract project.

### Bug

```bash
➜  counter git:(master) ✗ nargo fmt
Incompatible compiler version in package noir_aztec. Required compiler version is 0.1 but the compiler version is 0.18.0.
 Update the compiler_version field in Nargo.toml to >=0.18.0 or compile this project with version 0.18.0
```

This is my Nargo.toml

```toml
[package]
name = "counter_contract"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.13.1", directory="yarn-project/aztec-nr/aztec" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.13.1", directory="yarn-project/aztec-nr/value-note"}
easy_private_state = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.13.1", directory="yarn-project/aztec-nr/easy-private-state"}
```
using nargo version
```
➜  counter git:(master) ✗ nargo -V
nargo version = 0.18.0
noirc version = 0.18.0+9d9ee7a09ab972180dcb8ad59cdf1d6dd17e5794
(git version hash: 9d9ee7a09ab972180dcb8ad59cdf1d6dd17e5794, is dirty: false)
```

### To Reproduce

1. Clone the project [here](https://github.com/critesjosh/aztec-account-abstraction-workshop/tree/033df67ad27a022622d5adca049e9cd89adaa3d2/contracts/counter)
2. Install the latest version of Noir for aztec (v0.18.0-aztec.4)
3. run `nargo fmt` in the project

### Installation Method

None

### Would you like to submit a PR for this Issue?

No
