### ISSUE TITLE
Chained constructors give Expression type is ambiguous

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#4732]
### Aim

Code like this used to compile:
```rust
use dep::aztec::{prelude::{NoteViewerOptions, PrivateSet}};
use dep::value_note::value_note::ValueNote;

fn main() -> pub Field {
    let set: PrivateSet<ValueNote> = PrivateSet::new(dep::std::unsafe::zeroed(), 0);
    let options = NoteViewerOptions::new().set_limit(1); // chained construction happening here
    let notes = set.view_notes(options);
    notes[0].unwrap_unchecked().value
}
```
With this in dependencies:
```toml

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "master", directory = "noir-projects/aztec-nr/aztec" }
value_note = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "master", directory = "noir-projects/aztec-nr/value-note" }

```

Here is the code for NoteViewerOptions and private set:
https://github.com/AztecProtocol/aztec-packages/blob/master/noir-projects/aztec-nr/aztec/src/note/note_viewer_options.nr
https://github.com/AztecProtocol/aztec-packages/blob/master/noir-projects/aztec-nr/aztec/src/state_vars/private_set.nr

### Expected Behavior

I think it should compile, since the generic of NoteViewerOptions should be resolved to the generic of set that is ValueNote

### Bug

Instead it errors with `Expression type is ambiguous`

### To Reproduce

1.
2.
3.
4.

### Project Impact

Nice-to-have

### Workaround

Some

### Workaround Description

Splitting it in two lines works:
```rust
use dep::aztec::{prelude::{NoteViewerOptions, PrivateSet}};
use dep::value_note::value_note::ValueNote;

fn main() -> pub Field {
    let set: PrivateSet<ValueNote> = PrivateSet::new(dep::std::unsafe::zeroed(), 0);
    let mut options = NoteViewerOptions::new();
    options = options.set_limit(1);
    let notes = set.view_notes(options);
    notes[0].unwrap_unchecked().value
}
```

### Installation Method

None

### Would you like to submit a PR for this Issue?

None
