### ISSUE TITLE
Bug when using function return as function arg

### ISSUE THREAD

**Issue by okuyiga** [noir-lang/noir#628]
# Description

## Bug

Passing return value of some function into another function's args results in some weird behavior. See snippet.

# To reproduce

```toml
# Prover.toml
a=[3320379920, 1938147428, 1942509796, 1795943184, 24853, 0, 0, 0, 0]
b=[2912727897, 3590519536, 1687587470, 3896107618, 1092831095, 0, 0, 0, 0]
```
```rs
// main.rs
fn arr_to_field(arr: [u32; 9]) -> [Field; 9] {
    let mut as_field: [Field; 9] = [0 as Field; 9];
    for i in 0..9 {
        as_field[i] = arr[i] as Field;
    }
    as_field
}

fn foo(a: [Field; 9], b: [Field; 9]) -> [Field; 9] {
    a
}

fn main(a: [u32; 9], b: [u32; 9]) {
    let result = foo(arr_to_field(a), arr_to_field(b));
    
    // This does not work!
    // constrain result[0] == a[0] as Field;
    
    // This does!
    constrain result[0] == b[0] as Field;
}
```

# Environment

- OS: MacOS
