### ISSUE TITLE
Semver dependencies

### ISSUE THREAD

**Issue by olehmisar** [noir-lang/noir#7204]
### Problem

Specifying dependencies using semver instead of hardcoding github tag.

[Relevant discussion](https://discord.com/channels/1113924620781883405/1318787702681768009)

### Happy Case

I can specify dependencies like this:

```toml
[dependencies]
bignum = { version = "0.5.1" }
// or
bignum = { version = "=0.5.1" }
```

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None
