### ISSUE TITLE
ACIR vs Brillig: flattening + cast failed assertion; failed assertion on unreached branch

### ISSUE THREAD

**Issue by defkit** [noir-lang/noir#8558]
### Aim

Probably same as https://github.com/noir-lang/noir/issues/8557
```nr
fn main(v0: u64, v1: bool, v2: Field, v3: u64, v6: bool) -> pub u64 {
	let v7 = !v0;
	if v6 {
		let v8 = v6 - v1;
		let v9 = v2 * v2;
		let v10 = v9 / v2;
		let v11 = v3 + v7;
		if v8 {
			// b3
			let v14 = v3 - v11;
			let v16 = v14 as u32;
			let v17 = v16 + v16;
		} else {
			let v12 = v8 - v1;
			let v13 = v0 + v11;
		}
	}
	let v18 = v6 - v1;
	let v19 = v2 * v2;
	let v20 = v19 / v2;
	let v21 = v3 + v7;
	v21
}
```

```toml
"v6" = 0
"v0" = "18410433305400930673"
"v1" = 0
"v2" = "4298262607333352815191427808160790595428909340218062704704942964875637360905"
"v3" = "32954"
```

### Expected Behavior

ACIR solved

### `nargo execute`
```
error: Failed constraint
   ┌─ src/main.nr:11:14
   │
11 │             let v16 = v14 as u32;
   │                       ----------
   │
   = Call stack:
     1. src/main.nr:11:14

Failed to solve program: 'Cannot satisfy constraint'
```

### `nargo execute --force-brillig`
```
[noir_orig] Circuit witness successfully solved
[noir_orig] Witness saved to target/noir_orig.gz
[noir_orig] Circuit output: Field(36310768308653896)
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None
